/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// This file is auto-generated from apiJsonSchema.yml
// Do not edit this file directly - edit the YAML file instead

export const apiJsonSchema = {
  "title": "A JSON Schema for AlibabaCloud 1.0.0 API.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "apis"
  ],
  "additionalProperties": true,
  "properties": {
    "apis": {
      "$ref": "#/definitions/Apis"
    }
  },
  "definitions": {
    "SchemesList": {
      "type": "array",
      "description": "The transfer protocol of the API.",
      "items": {
        "type": "string",
        "enum": [
          "http",
          "https",
          "ws",
          "wss",
          "sse"
        ]
      },
      "uniqueItems": true
    },
    "SecurityRequirement": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "Apis": {
      "type": "object",
      "description": "存放所有api的map，map的key为api名称，需要为大驼峰。比如CreateInstance。",
      "patternProperties": {
        "^[A-Za-z0-9_.]+$": {
          "$ref": "#/definitions/Api"
        }
      },
      "additionalProperties": false,
      "errorMessage": {
        "additionalProperties": "should only have api names`"
      }
    },
    "Api": {
      "type": "object",
      "required": [
        "summary",
        "methods",
        "schemes"
      ],
      "properties": {
        "summary": {
          "type": "string",
          "description": "API的简短描述，用户未指定时，根据API的名称生成。比如API为CreateInstance，则描述为创建实例"
        },
        "path": {
          "type": "string",
          "description": "API的路径，这里永远不要自动生成"
        },
        "methods": {
          "type": "array",
          "description": "API的HTTP方法",
          "items": {
            "type": "string",
            "enum": [
              "get",
              "post",
              "put",
              "patch",
              "delete",
              "options",
              "head"
            ]
          },
          "uniqueItems": true
        },
        "schemes": {
          "$ref": "#/definitions/SchemesList"
        },
        "servers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Server"
          }
        },
        "consumes": {
          "description": "请求类型",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "produces": {
          "description": "响应类型",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "visibility": {
          "description": "API的可见性",
          "type": "string",
          "enum": [
            "Public",
            "Private",
            "SpecialPurpose"
          ]
        },
        "deprecated": {
          "type": "boolean"
        },
        "operationType": {
          "description": "API的读写类型",
          "type": "string",
          "enum": [
            "read",
            "write",
            "readAndWrite"
          ]
        },
        "apiTrailType": {
          "type": "string"
        },
        "staticInfo": {
          "type": "object",
          "properties": {
            "substitutions": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "noSubstitutionReason": {
              "type": "string"
            },
            "returnType": {
              "type": "string",
              "enum": [
                "synchronous",
                "asynchronous"
              ]
            },
            "callback": {
              "type": "string"
            },
            "callbackInterval": {
              "type": "integer"
            },
            "maxCallbackTimes": {
              "type": "integer"
            }
          }
        },
        "eventInfo": {
          "type": "object",
          "properties": {
            "enable": {
              "type": "boolean",
              "default": false
            },
            "eventNames": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "itGovernance": {
          "$ref": "#/definitions/ItGovernance"
        },
        "systemTags": {
          "type": "object",
          "properties": {
            "operationType": {
              "description": "生命周期，用户未指定时，根据API的名称推断生成。必须从下列的枚举中选值：create代表增、update代表修改、get代表查询、list代表列举、delete代表删除、none代表无。",
              "type": "string",
              "enum": [
                "create",
                "update",
                "get",
                "list",
                "delete",
                "none"
              ]
            },
            "riskType": {
              "description": "危险等级",
              "type": "string",
              "enum": [
                "high",
                "medium",
                "low",
                "none"
              ]
            },
            "chargeType": {
              "description": "付费类型",
              "type": "string",
              "enum": [
                "free",
                "paid",
                "none"
              ]
            },
            "abilityTreeCode": {
              "type": "string"
            },
            "abilityTreeNodes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "autoTest": {
              "type": "boolean"
            },
            "notSupportAutoTestReason": {
              "type": "string"
            },
            "tenantRelevance": {
              "type": "string",
              "enum": [
                "tenant",
                "publicInformation"
              ]
            }
          }
        },
        "security": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SecurityRequirement"
          }
        },
        "gatewayOptions": {
          "$ref": "#/definitions/GatewayOptions"
        },
        "backendService": {
          "$ref": "#/definitions/BackendService"
        },
        "clientBehavior": {
          "$ref": "#/definitions/ClientBehavior"
        },
        "policies": {
          "$ref": "#/definitions/Policies"
        },
        "errorMapping": {
          "$ref": "#/definitions/ErrorMapping"
        },
        "extErrorMapping": {
          "$ref": "#/definitions/ExtErrorMapping"
        },
        "parameters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Parameter"
          }
        },
        "responses": {
          "type": "object",
          "patternProperties": {
            "^[A-Za-z0-9]+$": {
              "$ref": "#/definitions/Response"
            }
          },
          "additionalProperties": false,
          "errorMessage": {
            "additionalProperties": "should only have response names`"
          }
        },
        "errorCodes": {
          "type": "object",
          "patternProperties": {
            "^[A-Za-z0-9]+$": {
              "$ref": "#/definitions/ErrorCodes"
            }
          },
          "additionalProperties": false,
          "errorMessage": {
            "additionalProperties": "should only have errorCodeList names`"
          }
        },
        "variables": {
          "type": "object",
          "patternProperties": {
            "^[A-Za-z0-9]+$": {
              "if": {
                "required": [
                  "$ref"
                ]
              },
              "then": {
                "$ref": "#/definitions/Reference"
              },
              "else": {
                "$ref": "#/definitions/Variables"
              }
            }
          },
          "additionalProperties": false,
          "errorMessage": {
            "additionalProperties": "should only have variables names`"
          }
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Variables": {
      "type": "object",
      "patternProperties": {
        "^\\$\\.[A-Za-z0-9\\.]+$": {}
      },
      "additionalProperties": false
    },
    "Parameter": {
      "type": "object",
      "required": [
        "name",
        "in",
        "schema"
      ],
      "properties": {
        "name": {
          "description": "入参的参数名称，需要为大驼峰，比如RequestId",
          "type": "string"
        },
        "in": {
          "description": "入参的参数位置",
          "type": "string",
          "enum": [
            "query",
            "header",
            "path",
            "formData",
            "body",
            "system",
            "bizSystem",
            "host",
            "const"
          ]
        },
        "allowEmptyValue": {
          "type": "boolean",
          "default": false
        },
        "style": {
          "type": "string",
          "enum": [
            "form",
            "simple",
            "spaceDelimited",
            "pipeDelimited",
            "repeatList",
            "flat",
            "json",
            "xml"
          ]
        },
        "schema": {
          "$ref": "#/definitions/Schema"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Example"
          }
        }
      },
      "additionalProperties": false
    },
    "Header": {
      "required": [
        "schema"
      ],
      "type": "object",
      "properties": {
        "allowEmptyValue": {
          "type": "boolean",
          "default": false
        },
        "style": {
          "type": "string",
          "enum": [
            "form",
            "simple",
            "spaceDelimited",
            "pipeDelimited",
            "repeatList",
            "json"
          ]
        },
        "schema": {
          "$ref": "#/definitions/Schema"
        }
      },
      "additionalProperties": false
    },
    "Response": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "headers": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "$ref": "#/definitions/Header"
            }
          },
          "additionalProperties": false
        },
        "schema": {
          "$ref": "#/definitions/Schema"
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "GatewayOptions": {
      "type": "object",
      "properties": {
        "flowControlResponseHeader": {
          "type": "boolean"
        },
        "ramAuth": {
          "type": "object",
          "properties": {
            "enable": {
              "type": "boolean"
            },
            "authLevel": {
              "type": "string"
            },
            "regionIdParamName": {
              "type": "string"
            },
            "authTypes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "ramCode": {
              "type": "string"
            },
            "ramAction": {
              "type": "string"
            },
            "ramArn": {
              "type": "string"
            }
          }
        },
        "apiAnnotations": {
          "type": "object",
          "properties": {
            "repeatListConflictValidation": {
              "type": "boolean"
            },
            "badInputJsonValidation": {
              "type": "boolean"
            },
            "badOutputJsonValidation": {
              "type": "boolean"
            },
            "maxRequestBodyConstraints": {
              "type": "integer",
              "format": "int32"
            },
            "remainEmptyArrayInJsonParameter": {
              "type": "boolean"
            }
          }
        },
        "rgOptions": {
          "type": "object",
          "properties": {
            "rgInterceptEnable": {
              "type": "boolean"
            }
          }
        },
        "tagOptions": {
          "type": "object",
          "properties": {
            "tagPolicyEnable": {
              "type": "boolean"
            },
            "tagCode": {
              "type": "string"
            },
            "tagParameterName": {
              "type": "string"
            },
            "tagParameterType": {
              "type": "string"
            },
            "tagResourceType": {
              "type": "string"
            },
            "tagResourceTypeParameterName": {
              "type": "string"
            },
            "tagResourceTypes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "showJsonItemName": {
          "type": "boolean"
        },
        "outputParamVersion": {
          "description": "出参版本，出参2.0时这里为2",
          "type": "integer",
          "format": "int32"
        },
        "optionalResponseFormats": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "defaultResponseFormat": {
          "type": "string"
        },
        "inputArrayAllowNull": {
          "type": "boolean"
        },
        "outputArrayAllowNull": {
          "type": "boolean"
        },
        "fileTransfer": {
          "type": "boolean"
        },
        "dataUpload": {
          "type": "boolean"
        },
        "dataDownload": {
          "type": "boolean"
        },
        "akProvenStatus": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "keepClientResourceOwnerId": {
          "type": "boolean"
        },
        "responseLog": {
          "describe": "记录返回日志",
          "type": "boolean"
        },
        "riskLevel": {
          "type": "string"
        },
        "isolationType": {
          "description": "API的隔离类型",
          "type": "string",
          "enum": [
            "inner",
            "outer"
          ]
        },
        "afterAuthService": {
          "type": "string"
        },
        "responseFilterPackage": {
          "type": "string"
        },
        "signatureComposer": {
          "type": "string"
        },
        "roaResponseBodyLog": {
          "description": "记录响应体日志",
          "type": "string",
          "enum": [
            "enable",
            "disable"
          ]
        },
        "roaRequestBodyLog": {
          "description": "记录请求体日志",
          "type": "string",
          "enum": [
            "enable",
            "disable"
          ]
        },
        "parameterSensitives": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "prefix": {
                "type": "string"
              },
              "suffix": {
                "type": "string"
              }
            }
          }
        },
        "responseSensitives": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "prefix": {
                "type": "string"
              },
              "suffix": {
                "type": "string"
              }
            }
          }
        },
        "userType": {
          "type": "string",
          "enum": [
            "inner",
            "outer"
          ]
        },
        "gatewayProtocols": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "BackendService": {
      "type": "object",
      "additionalProperties": true
    },
    "Policies": {
      "type": "object",
      "additionalProperties": true
    },
    "ErrorMapping": {
      "type": "object",
      "additionalProperties": true
    },
    "ExtErrorMapping": {
      "type": "object",
      "additionalProperties": true
    },
    "ErrorCodes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ErrorCode"
      }
    },
    "ErrorCode": {
      "type": "object",
      "additionalProperties": true
    },
    "ValueMapping": {
      "type": "object",
      "additionalProperties": true
    },
    "Schema": {
      "type": "object",
      "required": [
        "type",
        "backendName"
      ],
      "properties": {
        "sdkIgnore": {
          "type": "boolean"
        },
        "sdkPropertyName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "visibility": {
          "type": "string",
          "enum": [
            "Public",
            "Private",
            "SpecialPurpose",
            "cn",
            "intl",
            "jp"
          ]
        },
        "$ref": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "array",
            "boolean",
            "integer",
            "number",
            "object",
            "string",
            "any"
          ]
        },
        "format": {
          "type": "string",
          "enum": [
            "byte",
            "binary",
            "int32",
            "int64",
            "float",
            "double",
            "iso8601",
            "iso8601_normal",
            "timestamp"
          ]
        },
        "dateFormat": {
          "type": "string"
        },
        "properties": {
          "type": "object",
          "description": "存放所有参数的map，map的key为参数名称，需要为大驼峰，比如RegionId",
          "patternProperties": {
            "^[a-zA-Z0-9\\.\\-_]+$": {
              "$ref": "#/definitions/Schema"
            }
          }
        },
        "items": {
          "$ref": "#/definitions/Schema"
        },
        "deprecated": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "docRequired": {
          "type": "boolean"
        },
        "bizType": {
          "type": "string",
          "enum": [
            "normal",
            "system",
            "bizSystem"
          ]
        },
        "additionalProperties": {
          "$ref": "#/definitions/Schema"
        },
        "maximum": {
          "type": "string"
        },
        "exclusiveMaximum": {
          "type": "boolean"
        },
        "minimum": {
          "type": "string"
        },
        "exclusiveMinimum": {
          "type": "boolean"
        },
        "default": {
          "type": "string"
        },
        "enum": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "example": {
          "type": "string"
        },
        "maxLength": {
          "type": "integer",
          "minimum": 0
        },
        "minLength": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "pattern": {
          "type": "string",
          "format": "regex"
        },
        "maxItems": {
          "type": "integer",
          "minimum": 0
        },
        "minItems": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        },
        "uniqueItems": {
          "type": "boolean"
        },
        "maxProperties": {
          "type": "integer"
        },
        "minProperties": {
          "type": "integer"
        },
        "nullable": {
          "type": "boolean"
        },
        "readOnly": {
          "type": "boolean"
        },
        "writeOnly": {
          "type": "boolean"
        },
        "xml": {
          "$ref": "#/definitions/Xml"
        },
        "extensions": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z0-9\\.\\-_]+$": {}
          }
        },
        "checkBlank": {
          "type": "boolean"
        },
        "nullToEmpty": {
          "type": "boolean"
        },
        "timestampToDate": {
          "type": "boolean"
        },
        "emptyToNull": {
          "type": "boolean"
        },
        "repeatListSequence": {
          "type": "boolean"
        },
        "backendPosition": {
          "type": "string",
          "enum": [
            "header",
            "query",
            "path",
            "body"
          ]
        },
        "repeatListDataType": {
          "type": "string"
        },
        "repeatListIndexName": {
          "type": "string"
        },
        "repeatListSubName": {
          "type": "string"
        },
        "checkRepeatList": {
          "type": "boolean"
        },
        "backendName": {
          "description": "后端参数名称，当用户没有指定时，请根据入参名称或出参名称生成，生成规则为直接转换为小驼峰名称。比如入参或出参为\"RegionId\"，则生成的参数为regionId",
          "type": "string"
        },
        "index": {
          "type": "integer"
        },
        "groupIndex": {
          "type": "integer"
        },
        "parseJson": {
          "type": "boolean"
        },
        "parseType": {
          "type": "string"
        },
        "sensitive": {
          "type": "boolean"
        },
        "mappingType": {
          "type": "string"
        },
        "encodeType": {
          "type": "string"
        },
        "signed": {
          "type": "boolean"
        },
        "isFileTransferUrl": {
          "type": "boolean"
        },
        "codec": {
          "type": "string"
        },
        "itemName": {
          "type": "string"
        },
        "valueMapping": {},
        "trim": {
          "type": "boolean"
        },
        "extendType": {
          "type": "string"
        },
        "ext": {
          "type": "object"
        },
        "backendParamType": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "array"
              }
            }
          },
          "then": {
            "required": [
              "items"
            ]
          },
          "else": true
        }
      ]
    },
    "ItGovernance": {
      "type": "object",
      "properties": {
        "ram": {
          "$ref": "#/definitions/Ram"
        },
        "actionTrail": {
          "description": "操作审计",
          "$ref": "#/definitions/ActionTrail"
        }
      },
      "additionalProperties": false
    },
    "Ram": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "enable",
            "disable",
            "unknown"
          ]
        },
        "reason": {
          "type": "string"
        },
        "reasonText": {
          "type": "string"
        },
        "meta": {
          "authMethod": {
            "type": "string",
            "enum": [
              "gateway",
              "code"
            ]
          },
          "authLevel": {
            "type": "string",
            "enum": [
              "operate",
              "resource"
            ]
          },
          "authTypes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "operationType": {
            "type": "string"
          },
          "action": {
            "type": "string"
          },
          "resources": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "arn": {
                  "type": "string"
                },
                "namespace": {
                  "type": "string"
                },
                "resourceType": {
                  "type": "string"
                },
                "validationType": {
                  "type": "string",
                  "enum": [
                    "always",
                    "conditional"
                  ]
                },
                "expression": {
                  "type": "string"
                },
                "variables": {
                  "type": "object"
                }
              }
            }
          },
          "conditions": {
            "$ref": "#/definitions/RamCondition"
          },
          "additionalConditions": {
            "$ref": "#/definitions/RamCondition"
          }
        }
      },
      "additionalProperties": false
    },
    "RamCondition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string"
        },
        "validationType": {
          "type": "string",
          "enum": [
            "always",
            "conditional"
          ]
        },
        "expression": {
          "type": "string"
        },
        "relatedResourceIndexes": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "ActionTrail": {
      "type": "object",
      "properties": {
        "status": {
          "description": "是否开启操作审计",
          "type": "string",
          "enum": [
            "enable",
            "disable",
            "unknown"
          ]
        },
        "reason": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
} as const;

export default apiJsonSchema;
